version: '3'
services:
  mysql5:
    image: mysql:5.7
    container_name: mysql5
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
    ports:
      - 3306:3306
    volumes:
      - mysql5-storage:/var/lib/mysql
volumes:
  mysql5-storage:
